#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../high-scores-check ../high-scores ../high-scores-toplevel ; else ./runt "$@" ../high-scores-check ../high-scores ../high-scores-toplevel ; fi
cd - 2>&1 >/dev/null
