#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../accumulate-check ../accumulate ../accumulate-toplevel accumulate-funcs ; else ./runt $@ ../accumulate-check ../accumulate ../accumulate-toplevel accumulate-funcs ; fi
cd - 2>&1 >/dev/null
