#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../isbn-verifier-check ../isbn-verifier ../isbn-verifier-toplevel isbn-verifier-funcs ; else ./runt "$@" ../isbn-verifier-check ../isbn-verifier ../isbn-verifier-toplevel isbn-verifier-funcs ; fi
cd - 2>&1 >/dev/null
