#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../binary-search-check ../binary-search ../binary-search-toplevel binary-search-funcs ; else ./runt $@ ../binary-search-check ../binary-search ../binary-search-toplevel binary-search-funcs ; fi
cd - 2>&1 >/dev/null
