#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina protein-translation-check protein-translation protein-translation-toplevel ; else ./runt "$@" protein-translation-check protein-translation protein-translation-toplevel ; fi
