#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina roman-numerals-check roman-numerals roman-numerals-toplevel ; else ./runt "$@" roman-numerals-check roman-numerals roman-numerals-toplevel ; fi
