#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../matching-brackets-check ../matching-brackets ../matching-brackets-toplevel ; else ./runt "$@" ../matching-brackets-check ../matching-brackets ../matching-brackets-toplevel ; fi
cd - 2>&1 >/dev/null
