#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina matching-brackets-check matching-brackets matching-brackets-toplevel ; else ./runt "$@" matching-brackets-check matching-brackets matching-brackets-toplevel ; fi
