#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../secret-handshake-check ../secret-handshake ../secret-handshake-toplevel ; else ./runt "$@" ../secret-handshake-check ../secret-handshake ../secret-handshake-toplevel ; fi
cd - 2>&1 >/dev/null
