#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina secret-handshake-check secret-handshake secret-handshake-toplevel ; else ./runt "$@" secret-handshake-check secret-handshake secret-handshake-toplevel ; fi
