#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../nucleotide-count-check ../nucleotide-count ../nucleotide-count-toplevel ; else ./runt "$@" ../nucleotide-count-check ../nucleotide-count ../nucleotide-count-toplevel ; fi
cd - 2>&1 >/dev/null
