#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina nucleotide-count-check nucleotide-count nucleotide-count-toplevel ; else ./runt "$@" nucleotide-count-check nucleotide-count nucleotide-count-toplevel ; fi
