#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../phone-number-check ../phone-number ../phone-number-toplevel ; else ./runt "$@" ../phone-number-check ../phone-number ../phone-number-toplevel ; fi
cd - 2>&1 >/dev/null
