#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../proverb-check ../proverb ../proverb-toplevel proverb-funcs ; else ./runt "$@" ../proverb-check ../proverb ../proverb-toplevel proverb-funcs ; fi
cd - 2>&1 >/dev/null
