#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../list-ops-check ../list-ops ../list-ops-toplevel list-ops-funcs ; else ./runt $@ ../list-ops-check ../list-ops ../list-ops-toplevel list-ops-funcs ; fi
cd - 2>&1 >/dev/null
