#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../rotational-cipher-check ../rotational-cipher ../rotational-cipher-toplevel rotational-cipher-funcs ; else ./runt $@ ../rotational-cipher-check ../rotational-cipher ../rotational-cipher-toplevel rotational-cipher-funcs ; fi
cd - 2>&1 >/dev/null
