#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina rotational-cipher-check rotational-cipher rotational-cipher-toplevel ; else ./runt "$@" rotational-cipher-check rotational-cipher rotational-cipher-toplevel ; fi
