#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../rotational-cipher-check ../rotational-cipher ../rotational-cipher-toplevel ; else ./runt "$@" ../rotational-cipher-check ../rotational-cipher ../rotational-cipher-toplevel ; fi
cd - 2>&1 >/dev/null
