#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../pangram-check ../pangram ../pangram-toplevel ; else ./runt "$@" ../pangram-check ../pangram ../pangram-toplevel ; fi
cd - 2>&1 >/dev/null
