#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../beer-song-check ../beer-song ../beer-song-toplevel beer-song-funcs ; else ./runt $@ ../beer-song-check ../beer-song ../beer-song-toplevel beer-song-funcs ; fi
cd - 2>&1 >/dev/null
