#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../beer-song-check ../beer-song ../beer-song-toplevel ; else ./runt "$@" ../beer-song-check ../beer-song ../beer-song-toplevel ; fi
cd - 2>&1 >/dev/null
