#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../hamming-check ../hamming ../hamming-toplevel hamming-funcs ; else ./runt "$@" ../hamming-check ../hamming ../hamming-toplevel hamming-funcs ; fi
cd - 2>&1 >/dev/null
