#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../house-check ../house ../house-toplevel ; else ./runt "$@" ../house-check ../house ../house-toplevel ; fi
cd - 2>&1 >/dev/null
