#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina sum-of-multiples-check sum-of-multiples sum-of-multiples-toplevel ; else ./runt "$@" sum-of-multiples-check sum-of-multiples sum-of-multiples-toplevel ; fi
