#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../sum-of-multiples-check ../sum-of-multiples ../sum-of-multiples-toplevel ; else ./runt "$@" ../sum-of-multiples-check ../sum-of-multiples ../sum-of-multiples-toplevel ; fi
cd - 2>&1 >/dev/null
