#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../atbash-cipher-check ../atbash-cipher ../atbash-cipher-toplevel atbash-cipher-funcs ; else ./runt "$@" ../atbash-cipher-check ../atbash-cipher ../atbash-cipher-toplevel atbash-cipher-funcs ; fi
cd - 2>&1 >/dev/null
