#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../leap-check ../leap ../leap-toplevel leap-funcs ; else ./runt "$@" ../leap-check ../leap ../leap-toplevel leap-funcs ; fi
cd - 2>&1 >/dev/null
