#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../error-handling-check ../error-handling ../error-handling-toplevel ; else ./runt "$@" ../error-handling-check ../error-handling ../error-handling-toplevel ; fi
cd - 2>&1 >/dev/null
