#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina error-handling-check error-handling error-handling-toplevel ; else ./runt "$@" error-handling-check error-handling error-handling-toplevel ; fi
