#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../matrix-check ../matrix ../matrix-toplevel matrix-funcs ; else ./runt "$@" ../matrix-check ../matrix ../matrix-toplevel matrix-funcs ; fi
cd - 2>&1 >/dev/null
