#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../prime-factors-check ../prime-factors ../prime-factors-toplevel prime-factors-funcs ; else ./runt $@ ../prime-factors-check ../prime-factors ../prime-factors-toplevel prime-factors-funcs ; fi
cd - 2>&1 >/dev/null
