#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../bank-account-check ../bank-account ../bank-account-toplevel ; else ./runt "$@" ../bank-account-check ../bank-account ../bank-account-toplevel ; fi
cd - 2>&1 >/dev/null
