#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../simple-cipher-check ../simple-cipher ../simple-cipher-toplevel ; else ./runt "$@" ../simple-cipher-check ../simple-cipher ../simple-cipher-toplevel ; fi
cd - 2>&1 >/dev/null
