#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../anagram-check ../anagram ../anagram-toplevel anagram-funcs ; else ./runt "$@" ../anagram-check ../anagram ../anagram-toplevel anagram-funcs ; fi
cd - 2>&1 >/dev/null
