#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../isogram-check ../isogram ../isogram-toplevel ; else ./runt "$@" ../isogram-check ../isogram ../isogram-toplevel ; fi
cd - 2>&1 >/dev/null
