#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../square-root-check ../square-root ../square-root-toplevel ; else ./runt "$@" ../square-root-check ../square-root ../square-root-toplevel ; fi
cd - 2>&1 >/dev/null
