#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../raindrops-check ../raindrops ../raindrops-toplevel raindrops-funcs ; else ./runt $@ ../raindrops-check ../raindrops ../raindrops-toplevel raindrops-funcs ; fi
cd - 2>&1 >/dev/null
