#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../raindrops-check ../raindrops ../raindrops-toplevel ; else ./runt "$@" ../raindrops-check ../raindrops ../raindrops-toplevel ; fi
cd - 2>&1 >/dev/null
