#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina resistor-color-check resistor-color resistor-color-toplevel ; else ./runt "$@" resistor-color-check resistor-color resistor-color-toplevel ; fi
