#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../resistor-color-check ../resistor-color ../resistor-color-toplevel ; else ./runt "$@" ../resistor-color-check ../resistor-color ../resistor-color-toplevel ; fi
cd - 2>&1 >/dev/null
