#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../all-your-base-check ../all-your-base ../all-your-base-toplevel ; else ./runt "$@" ../all-your-base-check ../all-your-base ../all-your-base-toplevel ; fi
cd - 2>&1 >/dev/null
