#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../space-age-check ../space-age ../space-age-toplevel ; else ./runt "$@" ../space-age-check ../space-age ../space-age-toplevel ; fi
cd - 2>&1 >/dev/null
