#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../custom-set-check ../custom-set ../custom-set-toplevel custom-set-funcs ; else ./runt "$@" ../custom-set-check ../custom-set ../custom-set-toplevel custom-set-funcs ; fi
cd - 2>&1 >/dev/null
