#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../queen-attack-check ../queen-attack ../queen-attack-toplevel ; else ./runt "$@" ../queen-attack-check ../queen-attack ../queen-attack-toplevel ; fi
cd - 2>&1 >/dev/null
