#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../difference-of-squares-check ../difference-of-squares ../difference-of-squares-toplevel difference-of-squares-funcs ; else ./runt "$@" ../difference-of-squares-check ../difference-of-squares ../difference-of-squares-toplevel difference-of-squares-funcs ; fi
cd - 2>&1 >/dev/null
