#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina difference-of-squares-check difference-of-squares difference-of-squares-toplevel ; else ./runt "$@" difference-of-squares-check difference-of-squares difference-of-squares-toplevel ; fi
