#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../reverse-string-check ../reverse-string ../reverse-string-toplevel reverse-string-funcs ; else ./runt $@ ../reverse-string-check ../reverse-string ../reverse-string-toplevel reverse-string-funcs ; fi
cd - 2>&1 >/dev/null
