#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina reverse-string-check reverse-string reverse-string-toplevel ; else ./runt "$@" reverse-string-check reverse-string reverse-string-toplevel ; fi
