#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../triangle-check ../triangle ../triangle-toplevel triangle-funcs ; else ./runt "$@" ../triangle-check ../triangle ../triangle-toplevel triangle-funcs ; fi
cd - 2>&1 >/dev/null
