#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../triangle-check ../triangle ../triangle-toplevel ; else ./runt "$@" ../triangle-check ../triangle ../triangle-toplevel ; fi
cd - 2>&1 >/dev/null
