#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../darts-check ../darts ../darts-toplevel ; else ./runt "$@" ../darts-check ../darts ../darts-toplevel ; fi
cd - 2>&1 >/dev/null
