#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../acronym-check ../acronym ../acronym-toplevel acronym-funcs ; else ./runt $@ ../acronym-check ../acronym ../acronym-toplevel acronym-funcs ; fi
cd - 2>&1 >/dev/null
