#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina scrabble-score-check scrabble-score scrabble-score-toplevel ; else ./runt "$@" scrabble-score-check scrabble-score scrabble-score-toplevel ; fi
