#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../scrabble-score-check ../scrabble-score ../scrabble-score-toplevel ; else ./runt "$@" ../scrabble-score-check ../scrabble-score ../scrabble-score-toplevel ; fi
cd - 2>&1 >/dev/null
