#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../nth-prime-check ../nth-prime ../nth-prime-toplevel nth-prime-funcs ; else ./runt "$@" ../nth-prime-check ../nth-prime ../nth-prime-toplevel nth-prime-funcs ; fi
cd - 2>&1 >/dev/null
