#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../two-fer-check ../two-fer ../two-fer-toplevel ; else ./runt "$@" ../two-fer-check ../two-fer ../two-fer-toplevel ; fi
cd - 2>&1 >/dev/null
