#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../saddle-points-check ../saddle-points ../saddle-points-toplevel ; else ./runt "$@" ../saddle-points-check ../saddle-points ../saddle-points-toplevel ; fi
cd - 2>&1 >/dev/null
