#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../armstrong-numbers-check ../armstrong-numbers ../armstrong-numbers-toplevel ; else ./runt "$@" ../armstrong-numbers-check ../armstrong-numbers ../armstrong-numbers-toplevel ; fi
cd - 2>&1 >/dev/null
