#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina armstrong-numbers-check armstrong-numbers armstrong-numbers-toplevel ; else ./runt "$@" armstrong-numbers-check armstrong-numbers armstrong-numbers-toplevel ; fi
