#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina collatz-conjecture-check collatz-conjecture collatz-conjecture-toplevel ; else ./runt "$@" collatz-conjecture-check collatz-conjecture collatz-conjecture-toplevel ; fi
