#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../collatz-conjecture-check ../collatz-conjecture ../collatz-conjecture-toplevel collatz-conjecture-funcs ; else ./runt $@ ../collatz-conjecture-check ../collatz-conjecture ../collatz-conjecture-toplevel collatz-conjecture-funcs ; fi
cd - 2>&1 >/dev/null
