#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../grains-check ../grains ../grains-toplevel grains-funcs ; else ./runt $@ ../grains-check ../grains ../grains-toplevel grains-funcs ; fi
cd - 2>&1 >/dev/null
