#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../sublist-check ../sublist ../sublist-toplevel ; else ./runt "$@" ../sublist-check ../sublist ../sublist-toplevel ; fi
cd - 2>&1 >/dev/null
