#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../perfect-numbers-check ../perfect-numbers ../perfect-numbers-toplevel perfect-numbers-funcs ; else ./runt $@ ../perfect-numbers-check ../perfect-numbers ../perfect-numbers-toplevel perfect-numbers-funcs ; fi
cd - 2>&1 >/dev/null
