#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina perfect-numbers-check perfect-numbers perfect-numbers-toplevel ; else ./runt "$@" perfect-numbers-check perfect-numbers perfect-numbers-toplevel ; fi
