#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../sieve-check ../sieve ../sieve-toplevel sieve-funcs ; else ./runt "$@" ../sieve-check ../sieve ../sieve-toplevel sieve-funcs ; fi
cd - 2>&1 >/dev/null
