#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../luhn-check ../luhn ../luhn-toplevel ; else ./runt "$@" ../luhn-check ../luhn ../luhn-toplevel ; fi
cd - 2>&1 >/dev/null
