#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../etl-check ../etl ../etl-toplevel ; else ./runt "$@" ../etl-check ../etl ../etl-toplevel ; fi
cd - 2>&1 >/dev/null
