#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../transpose-check ../transpose ../transpose-toplevel ; else ./runt "$@" ../transpose-check ../transpose ../transpose-toplevel ; fi
cd - 2>&1 >/dev/null
