#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../bob-check ../bob ../bob-toplevel bob-funcs ; else ./runt "$@" ../bob-check ../bob ../bob-toplevel bob-funcs ; fi
cd - 2>&1 >/dev/null
