#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../resistor-color-duo-check ../resistor-color-duo ../resistor-color-duo-toplevel ; else ./runt "$@" ../resistor-color-duo-check ../resistor-color-duo ../resistor-color-duo-toplevel ; fi
cd - 2>&1 >/dev/null
