#!/usr/bin/env bash
if [ $# -eq 0 ] ; then ./runt --regina resistor-color-duo-check resistor-color-duo resistor-color-duo-toplevel ; else ./runt "$@" resistor-color-duo-check resistor-color-duo resistor-color-duo-toplevel ; fi
