#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../twelve-days-check ../twelve-days ../twelve-days-toplevel ; else ./runt "$@" ../twelve-days-check ../twelve-days ../twelve-days-toplevel ; fi
cd - 2>&1 >/dev/null
