#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../twelve-days-check ../twelve-days ../twelve-days-toplevel twelve-days-funcs ; else ./runt $@ ../twelve-days-check ../twelve-days ../twelve-days-toplevel twelve-days-funcs ; fi
cd - 2>&1 >/dev/null
