# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/test

name: rexx / Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Regina Rexx
        run: |
            sudo apt update && sudo apt -y install curl
            curl -sLk https://sourceforge.net/projects/regina-rexx/files/regina-rexx/3.9.5/regina-rexx_3.9.5-2_amd64-Debian-11.deb > regina-rexx_3.9.5-2_amd64-Debian-11.deb
            curl -sLk https://sourceforge.net/projects/regina-rexx/files/regina-rexx/3.9.5/libregina3_3.9.5-2_amd64-Debian-11.deb > libregina3_3.9.5-2_amd64-Debian-11.deb
            sudo apt -y install ./libregina3_3.9.5-2_amd64-Debian-11.deb ./regina-rexx_3.9.5-2_amd64-Debian-11.deb

      - name: Verify all exercises
        run: bash bin/verify-exercises
