#!/usr/bin/env bash
cd "testlib" 2>&1 >/dev/null
if [ $# -eq 0 ] ; then ./runt --regina ../clock-check ../clock ../clock-toplevel ; else ./runt "$@" ../clock-check ../clock ../clock-toplevel ; fi
cd - 2>&1 >/dev/null
